### ISSUE TITLE
Add a LICENSE.md file

### ISSUE THREAD

**Issue by SqTH** [modopro76/Patch-FR-SCP-Secret-Laboratory-DestinyGaming#2]
What is the licence upon the translation you publicly provide?

KR

**Comment by modopro76** [comment]
Hello,

I dont have licence attached on my translation.

**Comment by SqTH** [comment]
So you are aware that without any license attached, you retain all rights to your translation and we can't reproduce, distribute, or create derivative works from your work. Right?

**Comment by modopro76** [comment]
With no licence you can modify no ?

**Comment by SqTH** [comment]
No. Seen you accepted the Terms of Use of GitHub, that your repository is public and you didn't specified any license, all we can do is look at the code, and fork it. Not specifying a license does not imply means that we are permitted to use/modify/share the content for any purpose.

Id you don't want any license on your translation, may I suggest the cc0-1.0 license (https://choosealicense.com/licenses/cc0-1.0/"). Otherwise, kindly please specify what license you wish to apply on your repository.

Kind Regards,

**Comment by modopro76** [comment]
Done

**Comment by SqTH** [comment]
Great, thank you!!
