### ISSUE TITLE
Add translation to game

### ISSUE THREAD

**Issue by SqTH** [modopro76/Patch-FR-SCP-Secret-Laboratory-DestinyGaming#3]
https://github.com/northwood-studios/SCPSL-Translations

There you go

**Comment by modopro76** [comment]
Hello SqTH, 

Thank you for your comment.
I add this tomorrow. I check in game and I send my translation to a pull request.

Best regards,

Modopro

**Comment by modopro76** [comment]
Hello,

I have share my translation with your github page.

Best regards,

Modopro
